ALTER TABLE app_settings
  ADD COLUMN IF NOT EXISTS sso_admin_group TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sso_editor_group TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sso_viewer_group TEXT NOT NULL DEFAULT '';
